#:schema node_modules/wrangler/config-schema.json
name = "frontend"
main = ".open-next/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }


[env.dev]
routes = [
  { pattern = "prokushev.com", custom_domain = true },
]
[observability.logs]
enabled = true

kv_namespaces = [
  { binding = "NEXT_CACHE_WORKERS_KV", id = "baf390e9956244f18d95dc9422603ec4" },
]
