on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Configure
        run: |
          if [ ${{ env.BRANCH }} == 'dev' ]; then
            rm .env.production
            cp .env.development .env.production
          fi
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
          preCommands: NODE_ENV=${{ env.BRANCH == 'dev' && 'development' || 'production' }} npm run build:worker
          command: deploy --env ${{ env.BRANCH }}
